### ISSUE TITLE
Consider giving sentiment scores for BTC

### ISSUE THREAD

**Issue by fahadshery** [cryptomood/api#4]
Hi,

You are giving sentiment scores for the app but not the API for `BTC`. I think people will be able to try this more because we want to test if your sentiment scores have any correlation for the BTC or not which I can't test having a Free account.

Just a thought and a request!

Cheers
Fahad

**Comment by cryptomood** [comment]
Hey Fahad!

Thank you so much for your thoughts! We seriously appreciate it. While we don't currently offer access to sentiment scores for the BTC API to free users, this feature will be available some time in July. Note that we also offer APIs for BCH, ETH, and LTC (if you're interested). 

Please let us know if you have any other ideas!!

CryptoMood devs

**Comment by fahadshery** [comment]
Thank you for your prompt response. It was just a suggestion as we are new to automated trading and trying out different things. Feel free to close the issue. Good luck!
